NEWS_URL = "https://www.unipa.it/dipartimenti/ingegneria/cds/ingegneriainformatica2035"
NEWS_PATH = "/static/news/news.json"
NEWS_DEFAULT_PATH = "/static/news/defaultNews.json"
ANN_PATH = "/static/announcements/announcements.json"
ANN_DEFAULT_PATH = "/static/announcements/defaultAnnouncements.json"